### ISSUE TITLE
Create a server to handle requests

### ISSUE THREAD

**Issue by WikiWikiWasp** [WikiWikiWasp/Go-Message#2]
#### Description
Need to create a simple HTTP server that handles requests. It will serve up our HTML5 and JavaScript code as well as complete the setup of WebSocket connections from clients. Then make sure the server will also keep track of each WebSocket connection and relay chat messages sent from one client to all other clients connected by WebSocket.

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [x] Ensure `src` and `public` directories exist and `src` contains `main.go`
- [x] Import required packages
- [x] Create two global variables for connected clients and a channel for a message queue
- [x] Create WebSocket upgrader
- [x] Create object to hold messages
